[setting.aaveV3LendingPool]
description = "Address of the Aave v3 Lending Pool"

[setting.usdc]
description = "Address of the USDC ERC20 token"

[contract.AaveV3RateOracle_USDC]
artifact = "AaveV3RateOracle"
args=[
  "<%= settings.aaveV3LendingPool %>", # aaveLendingPool v3
  "<%= settings.usdc %>", # underlying
]

[contract.AaveV3BorrowRateOracle_USDC]
artifact = "AaveV3BorrowRateOracle"
args=[
  "<%= settings.aaveV3LendingPool %>", # aaveLendingPool v3
  "<%= settings.usdc %>", # underlying
]