# Deploys an initial Dated IRS Proxy so that a new Dated IRS Proxy is not 
# re-deployed every time we deploy a new router. Implementation is
# then upgraded to the correct Router implementation in the
# invoke.upgrade_dated_irs_proxy command below.
[contract.InitialDatedIrsProxy]
artifact = "ProductProxy"
args = ["<%= contracts.OwnerUpgradeModule.address %>", "<%= settings.owner %>"]
abiOf = ["OwnerUpgradeModule"]
salt = "<%= settings.salt %>"
create2 = true
depends = ["contract.OwnerUpgradeModule"]

# Upgrades implementation of Product IRS Proxy to point to the new 
# router implementation.
[invoke.upgrade_dated_irs_proxy]
target = ["InitialDatedIrsProxy"]
abi = "UpgradeModule"
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.DatedIrsRouter.address %>"]
factory.DatedIrsProxy.abiOf = ["DatedIrsRouter"]
factory.DatedIrsProxy.event = "Upgraded"
factory.DatedIrsProxy.arg = 0
depends = [
  "contract.InitialDatedIrsProxy",
  "router.DatedIrsRouter"
]