# Deploys an initial Product IRS Proxy so that a new Product IRS Proxy is not 
# re-deployed every time we deploy a new router. Implementation is
# then upgraded to the correct Router implementation in the
# invoke.upgrade_product_irs_proxy command below.
[contract.InitialDatedIRSProxy]
artifact = "ProductProxy"
args = ["<%= contracts.OwnerUpgradeModule.address %>", "<%= settings.owner %>"]
abiOf = ["OwnerUpgradeModule"]
salt = "<%= settings.salt %>"
create2 = true
depends = ["contract.OwnerUpgradeModule"]

# Upgrades implementation of Product IRS Proxy to point to the new 
# router implementation.
[invoke.upgrade_dated_irs_proxy]
target = ["InitialDatedIRSProxy"]
abi = "UpgradeModule"
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.ProductIRSRouter.address %>"]
factory.ProductIRSProxy.abiOf = ["ProductIRSRouter"]
factory.ProductIRSProxy.event = "Upgraded"
factory.ProductIRSProxy.arg = 0
depends = [
  "contract.InitialDatedIRSProxy",
  "router.ProductIRSRouter"
]