#####################################
# Deploy Dated IRS Router Modules
#####################################
[contract.MarketConfigurationModule]
artifact = "MarketConfigurationModule"
[contract.OwnerUpgradeModule]
artifact = "OwnerUpgradeModule"
[contract.ProductIRSModule]
artifact = "ProductIRSModule"
[contract.RateOracleManager]
artifact = "RateOracleManager"

# Deploys Product IRS Router
[router.ProductIRSRouter]
contracts = [
    "MarketConfigurationModule",
    "OwnerUpgradeModule",
    "ProductIRSModule",
    "RateOracleManager",
]
depends = [
  "contract.MarketConfigurationModule",
  "contract.OwnerUpgradeModule",
  "contract.ProductIRSModule",
  "contract.RateOracleManager",
]