#####################################
# Deploy Periphery Router Modules
#####################################
[contract.ConfigurationModule]
artifact = "ConfigurationModule"
[contract.ERC721ReceiverModule]
artifact = "ERC721ReceiverModule"
[contract.ExecutionModule]
artifact = "ExecutionModule"

# Deploys Periphery Router
[router.PeripheryRouter]
contracts = [
  "OwnerUpgradeModule",
  "ConfigurationModule",
  "ERC721ReceiverModule",
  "ExecutionModule",
]
depends = [
  "contract.OwnerUpgradeModule",
  "contract.ConfigurationModule",
  "contract.ERC721ReceiverModule",
  "contract.ExecutionModule",
]