# peripheryProxy is required and must be overridden
[setting.peripheryProxy]
description = "Address of the deployed Periphery Proxy"

# Upgrades implementation of Periphery Proxy to point to the new 
# router implementation.
[invoke.upgrade_periphery_proxy]
target = ["<%= settings.peripheryProxy %>"]
abi = "OwnerUpgradeModule"
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.PeripheryRouter.address %>"]
factory.PeripheryProxy.abiOf = ["PeripheryRouter"]
factory.PeripheryProxy.event = "Upgraded"
factory.PeripheryProxy.arg = 0
depends = [
  "router.PeripheryRouter"
]