plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs

nodeLinker: node-modules

npmRegistries:
  '//npm.pkg.github.com':
    npmAuthToken: ${secrets.GITHUB_TOKEN}