nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: "${secrets.GITHUB_TOKEN}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
