name = "voltz-core"
version = "2.0.0"
description = "Voltz V2 Core"

# `salt` here only affects proxy contract
[setting.salt]
description = "Change this to a unique string when deploying multiple instances of the protocol. Note that only the proxy contract will be unique."
defaultValue = "main"


[setting.owner]
description = "Admin user for the protocol"
defaultValue = "0xb527E950fC7c4F581160768f48b3bfA66a7dE1f0"


[contract.InitialModuleBundle]
artifact = "out/InitialModuleBundle.sol:InitialModuleBundle"
salt = "<%= settings.salt %>"
create2 = true

[contract.AccountModule]
artifact = "AccountModule"

[contract.AccountTokenModule]
artifact = "AccountTokenModule"

[contract.AssociatedSystemsModule]
artifact = "AssociatedSystemsModule"

[contract.CollateralConfigurationModule]
artifact = "CollateralConfigurationModule"

[contract.CollateralModule]
artifact = "CollateralModule"

[contract.LiquidationModule]
artifact = "LiquidationModule"

[contract.MulticallModule]
artifact = "MulticallModule"

[contract.ProductModule]
artifact = "ProductModule"

[contract.RiskConfigurationModule]
artifact = "RiskConfigurationModule"

# Core
[router.CoreRouter]
contracts = [
    "InitialModuleBundle",
    "AccountModule",
    "AssociatedSystemsModule",
    "CollateralModule",
    "CollateralConfigurationModule",
    "LiquidationModule",
    "MulticallModule",
    "RiskConfigurationModule",
    "ProductModule"
]

depends = [
  "contract.InitialModuleBundle",
  "contract.AccountModule",
  "contract.AssociatedSystemsModule",
  "contract.CollateralModule",
  "contract.CollateralConfigurationModule",
  "contract.LiquidationModule",
  "contract.MulticallModule",
  "contract.RiskConfigurationModule",
  "contract.ProductModule",
]

[contract.InitialCoreProxy]
artifact = "contracts/CoreProxy.sol:CoreProxy"
args = ["<%= contracts.InitialModuleBundle.address %>", "<%= settings.owner %>"]
abiOf = ["InitialModuleBundle"]
salt = "<%= settings.salt %>"
create2 = true
depends = ["contract.InitialModuleBundle"]

[invoke.upgrade_core_proxy]
target = ["InitialCoreProxy"]
abi = "UpgradeModule"
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.CoreRouter.address %>"]

factory.CoreProxy.abiOf = ["CoreRouter"]
factory.CoreProxy.event = "Upgraded"
factory.CoreProxy.arg = 0

depends = [
  "contract.InitialCoreProxy",
  "router.CoreRouter"
]

# Account
[router.AccountRouter]
contracts = [
    "InitialModuleBundle",
    "AccountTokenModule",
]
depends = [
  "contract.InitialModuleBundle",
  "contract.AccountTokenModule"
]

# Post actions