[profile.default]
  allow_paths = ["../", "../../", "../../node_modules/"]
  auto_detect_solc = false
  bytecode_hash = "none"
  cbor_metadata = false
  fuzz = { runs = 256, max_test_rejects = 1_000_000 }
  libs = ["lib", "../../node_modules"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.17"
  src = "src"
  test = "test"
  auto_detect_remappings = false

[profile.ci]
  fuzz = { runs = 1_000, max_test_rejects = 100_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 132
  multiline_func_header = "all"
  number_underscore = "preserve"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true