#####################################
# Deploys Account NFT Router Modules
#####################################
[contract.AccountTokenModule]
artifact = "AccountTokenModule"

# Deploys Account NFT Router. Proxy will be deployed
# by the Core Proxy (AssociatedSystemsModule) below.
[router.AccountNFTRouter]
contracts = [
    "OwnerUpgradeModule",
    "AccountTokenModule",
]
depends = [
  "contract.OwnerUpgradeModule",
  "contract.AccountTokenModule"
]