#####################################
# Deploy Core Router Modules
#####################################
[contract.AccessPassConfigurationModule]
artifact = "AccessPassConfigurationModule"
[contract.AccountModule]
artifact = "AccountModule"
[contract.AssociatedSystemsModule]
artifact = "AssociatedSystemsModule"
[contract.CollateralConfigurationModule]
artifact = "CollateralConfigurationModule"
[contract.CollateralModule]
artifact = "CollateralModule"
[contract.FeatureFlagModule]
artifact = "FeatureFlagModule"
[contract.FeeConfigurationModule]
artifact = "FeeConfigurationModule"
[contract.LiquidationModule]
artifact = "LiquidationModule"
[contract.PeripheryModule]
artifact = "PeripheryModule"
[contract.ProductModule]
artifact = "ProductModule"
[contract.RiskConfigurationModule]
artifact = "RiskConfigurationModule"

#####################################
# Deploy Core Router
#####################################
[router.CoreRouter]
contracts = [
  "OwnerUpgradeModule",
  "AccessPassConfigurationModule",
  "AccountModule",
  "AssociatedSystemsModule",
  "CollateralConfigurationModule",
  "CollateralModule",
  "FeatureFlagModule",
  "FeeConfigurationModule",
  "LiquidationModule",
  "PeripheryModule",
  "ProductModule",
  "RiskConfigurationModule"
]
depends = [
  "contract.OwnerUpgradeModule",
  "contract.AccessPassConfigurationModule",
  "contract.AccountModule",
  "contract.AssociatedSystemsModule",
  "contract.CollateralConfigurationModule",
  "contract.CollateralModule",
  "contract.FeatureFlagModule",
  "contract.FeeConfigurationModule",
  "contract.LiquidationModule",
  "contract.PeripheryModule",
  "contract.ProductModule",
  "contract.RiskConfigurationModule"
]