[profile.default]
  allow_paths = ["../", "../node_modules/"]
  auto_detect_solc = false
  fuzz = { runs = 256 }
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.19"
  src = "src"
  test = "test"
  auto_detect_remappings = false
  fs_permissions = [{ access = "read", path = "./"}]

[profile.ci]
  fuzz = { runs = 1_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true