name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Setup GitHub package registry"
        run: yarn config set npmRegistries --json '{"https://npm.pkg.github.com/":{"npmAuthToken":"${{secrets.NPM_AUTH_TOKEN}}"}}'
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      
      - name: Install dependencies
        run: yarn install
      
      - name: Bump versions
        run: yarn bump

      - name: "Change npm registry server"
        run: "yarn config set npmRegistryServer https://npm.pkg.github.com"
      
      - run: yarn publish