name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: yarn install
      - name: Create Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}