name: "Release"

on:
  push:
    branches:
      - main
      - feat/lerna-ci-pub

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: lerna run test
      - name: Configure Git and Bump Updated Packages
        run : |
          git config --global user.name "voltzprotocol"
          git config --global user.email "dev@voltz.xyz"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Voltz-Protocol/v2-off-chain-monorepo.git
          lerna run generate:coverage-badges 
          git add .
          git commit -m "chore: update coverage badges"
          lerna version
          git stash
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish packages with Lerna
        run: lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}